sudo: false

language: node_js
node_js:
  - 14
cache:
  directories:
    # I think it defaults to this:
    - node_modules
    # Default if "npm ci" were the script, but non-empty, so include it explicitly:
    - ~/.npm

before_script:
  - npm run install:avivator

script:
  - ./test.sh
