name: Test and build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install && npm run install:avivator
      - run: npm run build
      - run: npm run build:avivator
      - run: sudo apt-get install xvfb
      - run: xvfb-run --auto-servernum npm run test:prod

